source 'https://rubygems.org' do
  ruby '~> 2.7.4'

  gem 'nanoc'

  group :development do
    gem 'adsf'
    gem 'guard'
    gem 'byebug'
    gem 'awesome_print'
    gem 'i18n'
    gem "activesupport", ">= 6.0.3.1"
  end

  group :nanoc do
    gem 'guard-nanoc'
  end
end
