source "https://rubygems.org"

gem 'nanoc'

group :development do
  gem 'adsf'
  gem 'guard'
  gem 'byebug'
  gem 'awesome_print'
  gem 'i18n'
  gem 'activesupport'
end

group :nanoc do
  gem 'guard-nanoc'
end
